#!/usr/bin/perl -w
use warnings;
use strict;


use Net::Telnet ();
my $t = new Net::Telnet (Host => 'localhost', Port => '4242');
$t->open();
my @lines = $t->cmd('vimYo = content.window.pageYOffset;vimXo = content.window.pageXOffset;BrowserReload(); content.window.scrollTo(vimXo,vimYo);');
@lines = $t->cmd('repl.quit();');
 $t->close();
print @lines;
