#!/bin/sh

#  helper-untar.sh - Uncompress different tar files
#  
#  Copyright (c) 2010 Ben Leak <leakin.org>
#  taken from the 'expand-o-matic' from <http://www.ibm.com/developerworks/aix/library/au-spunixpower.html#expand>
# 
set -u
set -e

OPTIONS="\
    ./helper-untar.sh <filename>
"
input=

die(){
	echo >&2 "$@"
	exit 1
}
usage(){
	die "Usage: $0 $USAGE"
}
case "$#" in 0) usage ;; esac

if [ -f $1 ] ; then
case $1 in
  *.tar.bz2)   tar xvjf $1        ;;
  *.tar.gz)    tar xvzf $1     ;;
  *.bz2)       bunzip2 $1       ;;
  *.rar)       rar x $1     ;;
  *.gz)        gunzip $1     ;;
  *.tar)       tar xf $1        ;;
  *.tbz2)      tar xjf $1      ;;
  *.tgz)       tar xzf $1       ;;
  *.zip)       unzip $1     ;;
  *.Z)         uncompress $1  ;;
  *.7z)        7z x $1    ;;
  *)           echo "'$1' cannot be extracted via extract()" ;;
esac
else
echo "'$1' is not a valid file"
fi
