.TH GETSCRIPTS 1 "2011\[en]01\[en]16" 
.SH NAME
.PP
getscripts - get all scripts, omit binaries
.SH SYNOPSIS
.PP
getscripts [-f|\[em]format]
.SH OPTIONS
.IP \[bu] 2
--format= : Output formats are: html,pod,asciidoc,pandoc
.IP \[bu] 2
--help: Display help
.SH DESCRIPTION
.PP
Find scripts in system directories like /bin, /usr/bin
.SH AUTHORS
ben.

