#!/usr/local/bin/perl
# from http://www.evolt.org/article/Renaming_Files_with_Perl/17/351/
# Usage: rename perlexpr [files]
# eg. ./rename.pl 's/\.sh//' * - removes *.sh on each file

($regexp = shift @ARGV) || die "Usage:  rename perlexpr [filenames]\n";

if (!@ARGV) {
   @ARGV = <STDIN>;
   chomp(@ARGV);
}


foreach $_ (@ARGV) {
   $old_name = $_;
   eval $regexp;
   die $@ if $@;
   rename($old_name, $_) unless $old_name eq $_;
}

exit(0);

