#!/bin/sh

#     (c) 2011 Ben, untar.org
#
#
PROG=del
TITEL='trash for the cli, a save rm '
USAGE='<file>'

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

if [ "$#" = 0 ] ;then usage; fi
file="$1"

if [ ! -f "$file" ] && [ ! -d "$file" ] ; then
    echo "Error: '$file' is not a valid directory/file"
    exit 1
fi

trash="$HOME/trash/$(date +"%S%M%H%m%d%y")"
for f in $1;do 
   if [ ! -f "$trash/$f" ]; then 
        mkdir -p "$trash"
        mv "$f" "$trash/"
    else
        echo "Error: entry exists in $trash!!";
        exit 
 fi 
done 

