#!/bin/sh

#     (c) 2011 Ben, untar.org
#
PROG=gpglist
TITEL='an alias for: chmod 0755'
DESCRIPTION='list the keys in the private key ring'
USAGE='[public|private(default)]'

keys='private' # default value

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

if [ "$#" -gt 1 ] ; then
    usage
elif [ "$#" = 1 ] ; then
    keys="$1"
fi

case "$keys" in
    public)
        gpg --list-keys
        ;;
    private)
        gpg --list-secret-keys
        ;;
    *)
        usage
    ;;
esac

