#!/bin/sh

#     (c) 2011 Ben, untar.org
#
PROG=aptl
TITEL='show installed packages'
USAGE='<pattern>'

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

if [ "$#" = 0 ] ;then usage; fi
pat="$1"

dpkg --get-selections | awk '{ print $1 }' | grep "$pat"
