#!/bin/sh

#     (c) 2011 Ben, untar.org
#
PROG=aptr
TITEL='an alias for: sudo apt-get remove --purge <pattern>'
USAGE='<pattern>'

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

if [ "$#" = 0 ] ;then usage; fi
pat="$1"

sudo apt-get remove --purge "$pat"
