#!/bin/sh

#     (c) 2011 Ben, untar.org
#
PROG=grepi
TITEL='an alias for grep -lir'
USAGE='<searchpattern> <directory>'

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

dir= pat=
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ] ;then 
    usage 
elif [ "$#" -lt 2 ];then 
    pat="$1"
    dir="."
else
    pat="$1"
    dir="$2"
fi

if [ -d "$pat" ]; then
    temp="$dir"
    dir="$pat"
    pat="$temp"
elif [ ! -d "$dir" ];then
    echo "Error: '$dir' is not a valid directory"
    exit 1
fi

grep -lir "$pat" "$dir"
