#!/usr/bin/perl
# 
#  Generate file listing out of markdown files
#  ============================================
# 
#     Copyright (C) 2010 Ben
#
#     2010-10-18, leakin.org
#     tools/perl/html  
# 
#  --------------------------------------------
#
#  We have a bunch of markdown files ( *.md), and
#  we'd like to generate a file listing.
#  - generate .html files out of .md files 
#  - generate a file listing, item link to .html files

use strict;
use warnings;
use Getopt::Std;


our($opt_h,$opt_a);
sub usage {
my $msg = shift;
print "$msg\n";
print STDERR <<END;
Usage: $0    
	[-h]
	[-a files]
END
exit(1);
}

getopts("h:a") or usage();
usage() if $opt_h;

my $arg1 = $opt_a ||= "all";

my $filename = $ARGV[0] ;
if (not $filename) { 
    usage "Error: No filename given" ;
}

open( my $fh, '<', $filename ) or die "Can't open $filename: $!";
    while ( my $line = <$fh> ) {
        if ( $line =~ /wanted text/ ) {
            print $line;
        }
}
close $fh;


